apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: w49vhoat1-python 
  janus-idp.io/tekton: w49vhoat1-python
  backstage.io/kubernetes-id: w49vhoat1-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: w49vhoat1-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  